### ISSUE TITLE
アラーム停止アクションの実装

### ISSUE THREAD

**Issue by OiR-ptr** [OiR-ptr/Flutter_Alarm_exam#1]
アラーム停止を単なるボタンではなく､簡単な計算や何らかのアクションを要求し､成功時に停止する

**Comment by OiR-ptr** [comment]
とりあえず簡単な算数を解かないとアラームを止められないようにする
スヌーズ関係の動作をどうするかは一旦後回し

**Comment by OiR-ptr** [comment]
まずはSTOPボタンを押したら別ページに遷移するようにはできた
あとやることとしては､算数問題を出題することと､入力できるようにすること

回答ボタンを押して正答したらそのままナビゲーションをpopすることくらい？
STOPボタンを押した時点でアラームは止めてないとうるさくてだるい気がする

**Comment by oi-pst** [comment]
ひとまず、親ウィジェットから渡された固定の計算を解かないとアラーム停止しないようにはした

**Comment by oi-pst** [comment]
- [x] 計算問題を生成する
- [x] 出題数を設定可能にする
- [x] 難易度を設定可能にする
 ~~回答前にアラームは止め、１分無操作でスヌーズするようなことはできないか~~

**Comment by oi-pst** [comment]
二度寝防止用のアクション中スヌーズは別タスクで実装する
