### ISSUE TITLE
Snoozeを押しても解除アクション画面が開く

### ISSUE THREAD

**Issue by oi-pst** [OiR-ptr/Flutter_Alarm_exam#11]
よく見るので修正する

おそらくだが、解除アクション画面を開いている状態で再アラーム→スヌーズを押すとアクション画面に戻ってしまう

**Comment by OiR-ptr** [comment]
これ思ったより大変なバグかも。
Navigator関係の不具合だが、すべてpushReplacementで進ませようとするとアラーム鳴動画面が表示されなくなった。

🤮🤮🤮🤮🤮

**Comment by OiR-ptr** [comment]
[Navigator Observer](https://api.flutter.dev/flutter/widgets/NavigatorObserver-class.html) を使えばルーティング毎の処理ができるのでこちらを使うべき。
ただし、ページアイテムに対して何か処理が実行できるかは不明。
