### ISSUE TITLE
音声認識系アクションの実装

### ISSUE THREAD

**Issue by OiR-ptr** [OiR-ptr/Flutter_Alarm_exam#13]
音声認識を行うアクションを実装する
Flutter_soundのexampleにSimple recorderとrecordToStreamみたいなやつがあるので参考にする

**Comment by oi-pst** [comment]
レコーディング中にボリューム閾値が超えたらOKぐらいのものが良いと思う
ただし、Uint8Listに対して手を出すことができるかが疑問


pcm8形式にすればUint8が1サンプリング音となるので各種の計算がしやすくなるはず
無音が128で、0~127がマイナス波形、129+がプラス波形という感じになる

RMS値を計算して返してやれば大体よさそう
もしくはさらにlogしてdB変換するとか

**Comment by oi-pst** [comment]
PCM8はシミュレータだと対応していなかった
PCM系はベーシックなので大丈夫だと思っていたが、意外とそうでもないのかもしれない

**Comment by oi-pst** [comment]
以下参照。
Android/iOSでサポートが違うだけで機種差とかではないっぽい
https://flutter-sound.canardoux.xyz/guides_codec.html

**Comment by oi-pst** [comment]
PCM16とPCM16WAVの違いは不明。
多分だけどWAV用のメタデータヘッダが含まれているかどうか

**Comment by oi-pst** [comment]
https://github.com/alphacep/vosk-flutter
でもいいかもしれない

**Comment by OiR-ptr** [comment]
一旦保留
