### ISSUE TITLE
解除中の二度寝防止スヌーズ実装

### ISSUE THREAD

**Issue by OiR-ptr** [OiR-ptr/Flutter_Alarm_exam#3]
解除を試みる際に鳴りっぱなしだとうるさいのが問題
今後実装を考えている音声取得アクションにノイズが乗り散らかすかもなので、アクション中無音にする

**Comment by oi-pst** [comment]
ring.dartにてすでにアクション解除スヌーズは仕掛けてあるので、あとはアクション実行中のスヌーズだけ
math.dartについては、タスク繰り返し回数を設定できるようにしているのでタスク内でスヌーズを仕掛ければいい
