### ISSUE TITLE
顔認識系アクションの実装

### ISSUE THREAD

**Issue by oi-pst** [OiR-ptr/Flutter_Alarm_exam#8]
Google ML Kitのお試しの一環として、顔認識系の解除アクションを実装してみる

**Comment by oi-pst** [comment]
とりあえず見るプロパティが少ない、笑顔検出でアクションを作ってみようと思う

**Comment by oi-pst** [comment]
DetectorView > CameraView::_liveFeedBody あたりが主な処理ではあるが、どうやってるかいまいちわからない

大体はcamera_viewを見ればいいはず。。。

**Comment by oi-pst** [comment]
カメラの映像表示・笑顔度の取得まではできるようになった
あとは笑顔度を画面上に出力してあげればOK

ただ、カメラの映像は一度インスペクタを立ち上げないと画像が出ない。。。

**Comment by oi-pst** [comment]
アクション内容としては以下を想定
・難易度：笑顔と判定する閾値（0.5～0.9ぐらいを想定）
・タスク回数：笑顔を維持する秒数（1～3秒）

**Comment by oi-pst** [comment]
繰り返し回数とか言っておいて回数じゃないのはだめかもわからんね

**Comment by oi-pst** [comment]
難易度によって、笑顔と判定する閾値と秒数が決まる
そのうえで、そのタスクを何回こなすかにしてしまったほうがよさそう

**Comment by OiR-ptr** [comment]
> カメラの映像表示・笑顔度の取得まではできるようになった あとは笑顔度を画面上に出力してあげればOK
> 
> ただ、カメラの映像は一度インスペクタを立ち上げないと画像が出ない。。。

カメラが立ち上がったあとに空のsetStateを実行しないと初期化完了したことがわからないためだった
流れで修正済み

**Comment by oi-pst** [comment]
一旦、笑うと画面が切り替わって終わらせることができるようになった

あとは、カメラ映像上に「KEEP SMILE」の文字とCircularProgressIndicatorを表示すれば完成

**Comment by oi-pst** [comment]
KEEP SMILE+Indicatorを実装完了
指定された秒数、指定された回数、指定された閾値で笑顔を作らないと解除されないようになった

**Comment by oi-pst** [comment]
寝ている顔がsmileとして認識されると二度寝されてしまうので、何かしらの方法で防ぐ必要があるかもしれない
そもそも、終わりを押さないと終わらないので二度寝防止にはなってるかも

**Comment by oi-pst** [comment]
あとはデザインブラッシュアップに任せる
